### ISSUE TITLE
Strapi 4 support

### ISSUE THREAD

**Issue by yf-hk** [akcyp/strapi-plugin-point-list#1]

**Comment by akcyp** [comment]
V4 support is now available! However, Strapi does not natively support custom fields, so the current plugin implementation may be unstable. You can find more information here: https://github.com/strapi/documentation/issues/1062

**Comment by yf-hk** [comment]
> V4 support is now available! However, Strapi does not natively support custom fields, so the current plugin implementation may be unstable. You can find more information here: [strapi/documentation#1062](https://github.com/strapi/documentation/issues/1062)

Thanks for your response! Actually I don't use this plugin directly but as a reference, I'm developing a module which requires customizing the input component of a JSON field. After spending a few hours desperately searching for a solution, I somehow find a workaround, which definately isn't ideal but "works". Here's what I found:

1. Create a content type, add a `json` field (or `text` field in your case), specify a `componentType` (or whatever you'd like to call it):
```js
  "pluginOptions": {},
  "attributes": {
    "extra": {
      "type": "json",
      "componentType": "extra"
    }
  }
```

2. Create a plugin, during the `register` lifecycle ($pluginName/admin/src/index.js), overwrite the `json` field with your own component:
```js
    app.addFields([
      {
        type: 'json', Component: ExtraJSON
      },
    ]);
```

3.  In `ExtraJSON` component, check `props.attributes.componentType` field, if it's not `extra` then return the original `InputJSON` component, otherwise implement your own logic.

It works pretty well for me, but there is a problem though. It's a bit hacky, so if say another plugin also chooses to overwrite `json` field then there will be problems. But since I'm using a custom plugin just for our own website, it's not a big problem. It would be great if Strapi could support this feature natively.

**Comment by yf-hk** [comment]
Here's someone else's attampt (even more hacky which requires modifying the code in node_modules)
https://youtu.be/3of3s_xhEnE

**Comment by akcyp** [comment]
FYI, work on the new version is in progress :)

**Comment by akcyp** [comment]
Strapi v4 is supported
