### ISSUE TITLE
How to save Postgres Array type in v4 

### ISSUE THREAD

**Issue by kenanshrbage** [akcyp/strapi-plugin-point-list#4]
actually, i have done the same, but i have a problem, How can i save Postgres Array type in v4 
because in v3 it was in Column typ but i dono how can i do it.
can you help me please ?

**Comment by akcyp** [comment]
Hello @kenanshrbage.
Currently, the Strapi team is working on full support for custom fields, so far I will hold off on updating this plugin.
You can track updates there: https://feedback.strapi.io/developer-experience/p/custom-fields

**Comment by akcyp** [comment]
FYI, work on the new version is in progress :)

**Comment by akcyp** [comment]
Strapi v4 is supported now by default
